# Generated by Django 5.2.4 on 2025-10-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_rename_timestamp_tweet_created_at_and_more'),
    ]

    operations = [
    ]
